# Generated by Django 5.2.1 on 2025-05-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_year',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(through='sakila.FilmActor', to='sakila.actor'),
        ),
    ]
